name: pos
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.10+16

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  intl: ^0.19.0
  permission_handler: ^11.2.0
  pull_to_refresh: ^2.0.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.6
  get_storage: ^2.0.3
  cached_network_image: ^3.3.1
  json_annotation: ^4.7.0
  flutter_svg: ^2.0.9
  package_info_plus: ^5.0.1
  flutter_easyloading: ^3.0.5
  new_gradient_app_bar: ^0.2.0
  google_maps_flutter: ^2.5.0
  url_strategy: ^0.2.0
  calendar_date_picker2: ^0.5.3
  flutter_form_builder: ^9.1.1
  flutter_bloc: ^8.1.1
  go_router: ^13.2.4
  freezed_annotation: ^2.2.0
  device_info_plus: ^9.1.1
  flutter_html: ^3.0.0-beta.1
  webview_flutter: ^4.2.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  syncfusion_flutter_signaturepad: ^24.1.45
  multi_dropdown: ^2.1.3
  image: ^4.1.4
  firebase_auth: ^4.17.3
  google_sign_in: ^6.2.1
  firebase_core: ^2.25.3
  firebase_analytics: ^10.8.4
  dotted_border: ^2.1.0
  csc_picker: ^0.2.7
  flutter_slidable: ^3.0.1
  qr_flutter: ^4.1.0
  flutter_blue_plus: ^1.31.16
  bluetooth_print: ^4.3.0
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  flutter_cached_pdfview: ^0.4.2
  syncfusion_flutter_pdfviewer: ^24.2.7
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.5.3
  freezed: ^2.2.1

flutter_gen:
  output: lib/resources/

  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
